#!/usr/bin/env sh

## Disclaimer : This project was made as a hobby, please make sure to open an issue on my repo if you find any bug

set -euo pipefail

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
VIOLET=$(tput setaf 13)
LIME=$(tput setaf 14)
RESET=$(tput sgr0)

pkg_count(){
  local pkg_manager="$1"
  local cmd_count="$2"

  if ! command -v "$pkg_manager" &>/dev/null; then
    return
  fi
  if output=$($cmd_count 2>&1); then
      count=$(echo "$output" | wc -l)
      printf "%s " "$count" "($pkg_manager)"
  fi
}


sys(){
  
  local DISTRIBUTION=$(cat /etc/os-release | grep -i PRETTY_NAME | cut -d '=' -f2 | tr -d '"')
  local KERNEL_VERSION=$(uname -r)
  local KERNEL=$(uname -s)
  local OS=$(uname -o)
  local ARCHITECTURE=$(uname -m)
  local UPTIME=$(uptime -p | cut -d 'p' -f2)
  local SH=$(basename $SHELL)
  local INIT_SYSTEM=$(cat /proc/1/comm)
  local DATE=$(date | cut -d '+' -f1)
  local MACHINE=$(inxi -M | grep -i "product")
  local RESOLUTION=$(inxi -G | grep -i "resolution" | cut -d ':' -f2)
  local MACHINE_OUTPUT=$(echo ${MACHINE##*:})

  command -v inxi >/dev/null 2>&1 && echo "$BLUE* Machine:$RESET $MACHINE_OUTPUT" && echo "$BLUE* Display:$RESET $RESOLUTION"
  
  echo "$BLUE* OS:$RESET $DISTRIBUTION $ARCHITECTURE $OS"
  echo "$BLUE* Shell:$RESET $SH"
  echo "$BLUE* Kernel:$RESET $KERNEL $KERNEL_VERSION"
  echo "$BLUE* Desktop:$RESET $XDG_SESSION_DESKTOP ($XDG_SESSION_TYPE)"
  echo "$BLUE* Uptime:$RESET $UPTIME"
  
  printf "%s" "$BLUE* Packages: $RESET"
  pkg_count "dpkg" "dpkg -l"
  pkg_count "rpm" "dnf list --installed"
  pkg_count "pacman" "pacman -Q"
  pkg_count "pkg" "pkg info"
  pkg_count "zypp" "zypper se --installed-only"
  pkg_count "emerge" "qlist -I"
  pkg_count "apk" "apk info"
  pkg_count "flatpak" "flatpak list"
  pkg_count "snap" "snap list"
  pkg_count "brew" "brew list"
  echo ""
  echo "$BLUE* Date:$RESET $DATE"
  echo "$BLUE* Terminal:$RESET $TERM"
  echo "$BLUE* Init System:$RESET $INIT_SYSTEM"
}

swap(){
  
  local CSWAP_BYTES=$(free -h | awk 'NR==3 {print $3}' | tr -d '[0-9].')
  local SWAP_BYTES=$(free -h | awk 'NR==3 {print $2}' | tr -d '[0-9].')
  local CURRENT_SWAP=$(free -h | awk 'NR==3 {print $3}' | tr -d '[A-Z][a-z]')
  local SWAP=$(free -h | awk 'NR==3 {print $2}' | tr -d '[A-Z][a-z]')

  if [ $CSWAP_BYTES == 'Ki' ]; then
    AVG_SWAP=$(awk "BEGIN {printf(\"%.1f\", (1024 * $CURRENT_SWAP) / ($SWAP * 1073741824 + 0.0001) * 100)}" | cut -d '.' -f1)
  elif [ $CSWAP_BYTES == 'Mi' ]; then
    AVG_SWAP=$(awk "BEGIN {printf(\"%.1f\", (1048576 * $CURRENT_SWAP) / ($SWAP * 1073741824 + 0.0001) * 100)}" | cut -d '.' -f1)
  else
    AVG_SWAP=$(awk "BEGIN {printf(\"%.1f\", $CURRENT_SWAP / ($SWAP + 0.0001) * 100)}" | cut -d '.' -f1)
  fi

  if [ $AVG_SWAP -ge 75 ]; then
    echo "$BLUE* Swap:$RESET $CURRENT_SWAP$CSWAP_BYTES / $SWAP$SWAP_BYTES ($RED$AVG_SWAP%$RESET)"
  elif [ $AVG_SWAP -ge 55 ]; then
    echo "$BLUE* Swap:$RESET $CURRENT_SWAP$CSWAP_BYTES / $SWAP$SWAP_BYTES ($YELLOW$AVG_SWAP%$RESET)"
  else
    echo "$BLUE* Swap:$RESET $CURRENT_SWAP$CSWAP_BYTES / $SWAP$SWAP_BYTES ($GREEN$AVG_SWAP%$RESET)"
  fi

}


mem(){

  local UMEM_BYTES=$(free -h | awk 'NR==2 {print $3}' | tr -d '[0-9].')
  local MEM_BYTES=$(free -h | awk 'NR==2 {print $2}' | tr -d '[0-9].')
  local USED_MEMORY=$(free -h | awk 'NR==2 {print $3}'| tr -d '[A-Z][a-z]')
  local MEMORY=$(free -h | awk 'NR==2 {print $2}' | tr -d '[A-z][a-z]')
  
  if [ $UMEM_BYTES == 'Mi' ]; then
    AVG_MEMORY=$(awk "BEGIN {printf(\"%.1f\", (1048576 * $USED_MEMORY) / ($MEMORY + 1073741824 + 0.0001) * 100)}" | cut -d '.' -f1)
  else
    AVG_MEMORY=$(awk "BEGIN { printf(\"%.1f\", $USED_MEMORY / ($MEMORY + 0.0001) * 100)}" | cut -d '.' -f1)
  fi

   if [ $AVG_MEMORY -ge  75 ]; then
    echo "$BLUE* Memory:$RESET $USED_MEMORY$UMEM_BYTES / $MEMORY$MEM_BYTES ($RED$AVG_MEMORY%$RESET)"
  elif [ $AVG_MEMORY -ge 55 ]; then
    echo "$BLUE* Memory:$RESET $USED_MEMORY$UMEM_BYTES / $MEMORY$MEM_BYTES ($YELLOW$AVG_MEMORY%$RESET)"
  else
    echo "$BLUE* Memory:$RESET $USED_MEMORY$UMEM_BYTES / $MEMORY$MEM_BYTES ($GREEN$AVG_MEMORY%$RESET)"
  fi
  
}


brightness(){

  local ACTUAL_BRIGHTNESS=$(cat /sys/class/backlight/*_backlight/actual_brightness)
  local BRIGHTNESS=$(cat /sys/class/backlight/*_backlight/max_brightness)
  local CURRENT_BRIGHTNESS=$(awk "BEGIN { printf(\"%.1f\", $ACTUAL_BRIGHTNESS / $BRIGHTNESS * 100) }" | cut -d '.' -f1)
 

  if [ $CURRENT_BRIGHTNESS -gt 40 ]; then
    echo "$BLUE* Brightness:$RESET $GREEN$CURRENT_BRIGHTNESS%$RESET"
  elif [ $CURRENT_BRIGHTNESS -le 20 ]; then
    echo "$BLUE* Brightness:$RESET $RED$CURRENT_BRIGHTNESS%$RESET"
  else
    echo "$BLUE* Brightness:$RESET $YELLOW$CURRENT_BRIGHTNESS%$RESET"
  fi

}

battery(){
  
  local BATTERY=$(cat /sys/class/power_supply/BAT0/capacity)
  local BATTERY_STATUS=$(cat /sys/class/power_supply/BAT0/status)
  local BATTERY_MODEL=$(cat /sys/class/power_supply/BAT0/model_name)

   if [ $BATTERY -le 20 ]; then
    echo "$BLUE* Battery ($BATTERY_MODEL):$RESET $RED$BATTERY%$RESET [$RED$BATTERY_STATUS$RESET]"
  elif [ $BATTERY -gt 50 ]; then
    echo "$BLUE* Battery ($BATTERY_MODEL):$RESET $GREEN$BATTERY%$RESET [$GREEN$BATTERY_STATUS$RESET]"
  else
    echo "$BLUE* Battery ($BATTERY_MODEL):$RESET $YELLOW$BATTERY%$RESET [$YELLOW$BATTERY_STATUS$RESET]"
  fi

}


hw_infos(){
  local CPU=$(cat /proc/cpuinfo | grep -i "model name" | head -n  1 | cut -d ':' -f2)
  local PROC_NUMBERS=$(nproc)
  local PROCESSES=$(ps aux | wc -l)

  echo "$BLUE* CPU:$RESET $CPU ($PROC_NUMBERS)"
  echo "$BLUE* Processes:$RESET $PROCESSES"

}

disk(){

  local USED_DISK=$(df -h / | awk 'NR==2 {print $3}')
  local AVG_DISK=$(df -h / | awk 'NR==2 {print $5}')
  local CMP_DISK=$(df -h / | awk 'NR==2 {print $5}' | tr -d '%')
  local DISK=$(df -h / | awk 'NR==2 {print $2}')

   if [ $CMP_DISK -ge 75 ]; then
    echo "$BLUE* Disk:$RESET $USED_DISK / $DISK ($RED$AVG_DISK$RESET)"
  elif [ $CMP_DISK -ge 55 ]; then
    echo "$BLUE* Disk:$RESET $USED_DISK / $DISK ($YELLOW$AVG_DISK$RESET)"
  else
    echo "$BLUE* Disk:$RESET $USED_DISK / $DISK ($GREEN$AVG_DISK$RESET)"
  fi

}

network(){
  
  local LOCAL_IP=$(ip route | awk 'NR==2 {print $9}')
  local PROTOCOL=$(ip route | awk 'NR==2 {print $3}')
 
  echo "$BLUE* Local IP ($PROTOCOL):$RESET $LOCAL_IP"
  echo "$BLUE* Locale:$RESET $LANG"

}

sys_info() {
  sys
  battery
  brightness  
  hw_infos
  mem 
  swap
  disk
  network
 }

cat <<-EOF
  +-- $USER@$(hostname) --+
$(sys_info | sed 's/^/| /')

EOF


